from prompt.gen_prompts import RUN_PREDICTION_INPUT_DIRECT, RUN_PREDICTION_OUTPUT_DIRECT, RUN_PREDICTION_INPUT_COT, RUN_PREDICTION_OUTPUT_COT

SYSTEM_PROMPT = "You are a helpful assistant. Do NOT output any extra information."

__all__ = [
    "SYSTEM_PROMPT",
    "RUN_PREDICTION_INPUT_DIRECT",
    "RUN_PREDICTION_INPUT_COT",
    "RUN_PREDICTION_OUTPUT_DIRECT",
    "RUN_PREDICTION_OUTPUT_COT",
]