from prompt.generation_prompts import RUN_GENERATION, RUN_GENERATION_STANDARD
from prompt.prediction_prompts import RUN_PREDICTION_INPUT, RUN_PREDICTION_OUTPUT, RUN_PREDICTION_INPUT_COT, RUN_PREDICTION_OUTPUT_COT

__all__ = [
    "RUN_GENERATION",
    "RUN_GENERATION_STANDARD",
    "RUN_PREDICTION_INPUT",
    "RUN_PREDICTION_OUTPUT",
    "RUN_PREDICTION_INPUT_COT",
    "RUN_PREDICTION_OUTPUT_COT",
]